### ISSUE TITLE
rtr doesn't allow us to express backend_port?

### ISSUE THREAD

**Issue by menicosia** [cloudfoundry/routing-api-cli#11]
## What We Did

I ran the following:

> rtr register $(cat /tmp/rt.json) --api https://api.system-domain.com/ --skip-tls-verification --client-id tcp_emitter --client-secret 'REDACTED' --oauth-url https://uaa.sys-domain.com/

Where the contents of the JSON file are:
> [{"route":"tcp.system-domain.com","port":1034,"backend_port":3306,"ip":"10.0.8.5","ttl":60,"log_guid":"mysql_instance"}]

## What Happened

```
$ nc -v tcp.system-domain.com 1034
> Connection to tcp.pcf.hooliroof.com port 1034 [tcp/activesync] succeeded!
[No response]
```

## What We Expected

```
$ nc -v tcp.system-domain.com 1034
Connection to tcp.pcf.hooliroof.com port 1034 [tcp/activesync] succeeded!
Q
5.7.24-26-log�
kb%
```
(ie, the standard greeting string from a MySQL server).

## What we think is going on

The `rtr` documentation doesn't include `backend_port` in the documentation, and we worry that via `rtr` there's no way to specify this important piece of information to complete the loop.

We were able to get the expected behavior by calling the API directly:

```
#!/usr/bin/env bash

curl -vvv -H "Authorization: bearer REDACTED" \
  -X POST http://api.system-domain.com/routing/v1/tcp_routes/create -d '
[{
  "router_group_guid": "xxx-yyy",
  "port": 1034,
  "backend_ip": "10.0.8.5",
  "backend_port": 3306,
  "ttl": 120,
  "modification_tag":  {
    "guid": "qqq-ggg",
    "index": 1
  }
}]'
```

**Comment by dolfolife** [comment]
Thanks @menicosia 

We looked through it and unfortunately `rtr` doesn't support TCP routing commands. We want to know why you are trying to use CLI instead of HTTP API so we can see whether there is a need to add TCP routes support to `rtr`. Also, PRs are welcome!

Thanks!
@mike1808 and @rodolfo2488 , CF Networking Program Members

**Comment by menicosia** [comment]
Hi! I was using `rtr` as a way of exploring/spiking out how TCP Router
would work in our product. The CLI was convenient for doing a spike, but
ultimately wasted a bit of time because it seems to do the thing, but after
we wrestled with it a little bit, we realized that in fact it does not. :(

Instead we spent a reasonable amount of time puzzling over the API and got
things working with `curl` directly. This is more in-line with what we’d do
in production code, as I don’t think we’d prefer to call the CLI.

In general if the CLI could work for roughing things out in this way, our
use of routing’s release would go more smoothly.

**Comment by mike1808** [comment]
Hi @menicosia , we are sorry to hear about the time wasted trying to work with the cli. Unfortunately, we do not have plans to work on this, and given the amount of other prioritized work, it is unlikely this gets added. 

From an external perspective, would it be helpful if we added a loud note in the README specifying that tcp routing commands don't work? Otherwise, PR's are always welcome.

Thanks, 
@mike1808  and @KauzClay ,  CF Networking Program Members

**Comment by KauzClay** [comment]
We have updated the README with a note on the status of this project. We are closing the issue, but please re-open if you have other questions

Thanks, 
@KauzClay and @tcdowney , CF Networking Program Members
